extends RefCounted


const SORTS       = ["any","enemy","ally","player","attacker","flying","boss","ground"]
const COMPS       = ["==","not","<","<=",">",">=","===","always"]
const RADAR_KEYS  = ["distance","health","shield","armor","maxHealth"]
const OPS         = ["+","-","*","/","//","%","^","==","!=","&&","<","<=",">",">=","===","<<",">>",">>>",
					 "or","b-and","xor","flip","max","min","angle","angle-diff","len","noise",
					 "abs","sign","log","logn","log10","floor","ceil","round","sqrt","rand",
					 "sin","cos","tan","asin","acos","atan"]
const DRAW_MODES  = ["clear","color","col","stroke","line","rect","lineRect","polfoundy","linePoly",
					 "triangle","image","print","translate","scale","rotate","reset"]
var   ASCII:      = (" !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ" +
					 "[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~").split()


const COLORS: Dictionary = {
	"Controls":   Color(0.63,  0.347, 0),
	"Logics":     Color(0.257, 0.6,   0.66),
	"Operations": Color(0.391, 0.301, 0.64),
	"PutInOut":   Color(0.6,   0.555, 0.432),
	"Units":      Color(0.72,  0.637, 0.41),
}


static func _stub() -> void: pass


var BLOCKS: Dictionary = {
	"Controls": [
		{ name = "Drawflush",
		  template = tr("Drawflush to %in.display"),
		  options  = { display = { placeholder = "display1" } } },
		{ name = "Printflush",
		  template = tr("Printflush to %in.message"),
		  options  = { message = { placeholder = "message1" } } },
		{ name = "GetLink",
		  template = tr("GetLink %in.result = link# %in.link"),
		  options  = { result = { placeholder = "result" }, 
					   link = { placeholder = "0" } } },
		{ name = "Control",
		  template = tr("Control %op.mode %in.block to %in.index"),
		  options  = { mode = { items = ["enabled", "shoot", "shootp", "config", "color"], 
								changed = _stub },
					   block = { placeholder = "block1" },
					   index = { placeholder = "0" } } },
		{ name = "Radar",
		  template = tr("Radar from %in.turret %op.s1 %op.s2 %op.s3\norder %in.num sort %op.radar %in.result"),
		  options  = { turret = { placeholder = "turret1" }, 
					   s1 = { items = SORTS, changed = _stub },
					   s2 = { items = SORTS, changed = _stub },
					   s3 = { items = SORTS, changed = _stub },
					   num = { placeholder = "1" },
					   radar = { items = RADAR_KEYS, changed = _stub },
					   result = { placeholder = "result" } } },
		{ name = "Sensor",
		  template = tr("Sensor %in.result = %in.all in %in.block"),
		  options  = { result = { placeholder = "result" },
					   block = { placeholder = "block1" } } },
	],
	"Logics": [
		{ name = "Wait",
		  template = tr("Wait %in.time sec"),
		  options  = { time = { placeholder = "0.5" } } },
		{ name = "Stop",
		  template = tr("Stop"),
		  options  = {} },
		{ name = "End",
		  template = tr("End"),
		  options  = {} },
		{ name = "Jump",
		  template = tr("Jump %in.target if %in.value1 %op.cmp %in.value2"),
		  options  = { target = { placeholder = "0" },
					   value1 = { placeholder = "x" },
					   cmp = { items = COMPS, changed = _stub },
					   value2 = { placeholder = "false" } } },
		{ name = "JumpLabel",
		  template = tr("Label %in.label"),
		  options  = { label = { placeholder = "label1" } } },
		{ name = "Expression",
		  template = tr("Expression %in.text"),
		  options  = { value1 = { placeholder = "" } } },
		{ name = "If",
		  template = tr("If %in.a %op.cmp %in.b\n%li"),
		  options  = { a = { placeholder = "a" },
					   cmp = { items = COMPS, changed = _stub },
					   b = { placeholder = "b" } } },
	],
	"Operations": [
		{ name = "Set",
		  template = tr("Set %in.result = %in.value"),
		  options  = { result = { placeholder = "result" },
					   value = { placeholder = "0" } } },
		{ name = "Operation",
		  template = tr("Operation %in.result = %in.a %op.ops %in.b"),
		  options  = { result = { placeholder = "result" },
					   a = { placeholder = "a" },
					   ops = { items = OPS, changed = _stub },
					   b = { placeholder = "b" } } },
		{ name = "Select",
		  template = tr("Select %in.result = if %in.x %op.cmp %in.value\nthen %in.t else %in.f"),
		  options  = { result = { placeholder = "result" },
					   cmp = { items = COMPS, changed = _stub }, 
					   value = { placeholder = "false" }, 
					   t = { placeholder = "false" }, 
					   f = { placeholder = "false" } } },
		{ name = "Lookup",
		  template = tr("Lookup %in.result = lookup %op.type # %in.id"),
		  options  = { result = { placeholder = "result" },
					   type = { items = ["block","unit","item","liquid","team"], changed = _stub }, 
					   id = { placeholder = "0" } } },
		{ name = "PackColor",
		  template = tr("Pack Color %in.result = pack %in.r %in.g %in.b %in.a"),
		  options  = { result = { placeholder = "result" },
					   r = { placeholder = "1" }, 
					   g = { placeholder = "0" }, 
					   b = { placeholder = "0" }, 
					   a = { placeholder = "1" } } },
		{ name = "UnpackColor",
		  template = tr("Unpack Color %in.r %in.g %in.b %in.a = unpack %in.result"),
		  options  = { r = { placeholder = "r" }, 
					   g = { placeholder = "g" }, 
					   b = { placeholder = "b" }, 
					   a = { placeholder = "a" },
					   result = { placeholder = "result" } } },
	],
	"PutInOut": [
		{ name = "Read",
		  template = tr("Read %in.result = %in.cell at %in.idx"),
		  options  = { result = { placeholder = "result" },
					   cell = { placeholder = "cell1" }, 
					   idx = { placeholder = "0" } } },
		{ name = "Write",
		  template = tr("Write %in.result = %in.cell at %in.idx"),
		  options  = { result = { placeholder = "result" },
					   cell = { placeholder = "cell1" }, 
					   idx = { placeholder = "0" } } },
		{ name = "Draw",
		  template = tr("Draw %op.mode r %in.r g %in.g b %in.b"),
		  options  = { mode = { items = DRAW_MODES, changed = _stub },
					   r = { placeholder = "255" }, 
					   g = { placeholder = "0" }, 
					   b = { placeholder = "255" } } },
		{ name = "Print",
		  template = tr("Print %in.content %bu.txt"),
		  options  = { content = { placeholder = "frog" }, 
					   txt = { text = "txt", pressed = _stub } } },
		{ name = "PrintChar",
		  template = tr("PrintChar %op.char"),
		  options  = { char = { items = ASCII, changed = _stub } } },
		{ name = "Format",
		  template = tr("Format %in.content %bu.txt"),
		  options  = { content = { placeholder = "frog" }, 
					   txt = { text = "txt", pressed = _stub } } },
	],
	"Units": [
		{ name = "UnitBind",
		  template = tr("Unit Bind %in.all_poly"),
		  options  = {} },
		{ name = "UnitIdle",
		  template = tr("Unit idle"),
		  options  = {} },
		{ name = "UnitStop",
		  template = tr("Unit stop"),
		  options  = {} },
		{ name = "UnitMove",
		  template = tr("Unit CtrlMove %op.mode x %in.x y %in.y"),
		  options  = { mode = { items = ["move","approach","pathfind","autoPathfind"], changed = _stub },
					   x = { placeholder = "0" },
					   y = { placeholder = "0" } } },
		{ name = "UnitBoost",
		  template = tr("Unit CtrlBoost %in.id"),
		  options  = { id = { placeholder = "0" } } },
		{ name = "UnitShoot",
		  template = tr("Unit CtrlShoot %op.mode x %in.x y %in.y shoot %in.s"),
		  options  = { mode = { items = ["target","targetp"], changed = _stub },
					   x = { placeholder = "0" },
					   y = { placeholder = "0" },
					   s = { placeholder = "0" } } },
		{ name = "UnitItem",
		  template = tr("Unit CtrlItem %op.mode to %in.to amount %in.amount"),
		  options  = { mode = { items = ["itemDrop","itemTake"], changed = _stub },
					   to = { placeholder = "0" },
					   amount = { placeholder = "999" } } },
		{ name = "UnitPay",
		  template = tr("Unit CtrlPay %op.mode TakeUnits %in.unit"),
		  options  = { mode = { items = ["payTake","payDrop","payEnter"], changed = _stub },
					   unit = { placeholder = "0" } } },
		{ name = "UnitMine",
		  template = tr("Unit CtrlMine x %in.x y %in.y"),
		  options  = { x = { placeholder = "0" },
					   y = { placeholder = "0" } } },
		{ name = "UnitFlag",
		  template = tr("UnitFlag %in.id"),
		  options  = { id = { placeholder = "0" } } },
		{ name = "UnitBuild",
		  template = tr("Unit CtrlBuild x %in.x y %in.y\nblock %in.block rotation %in.rot config %in.cfg"),
		  options  = { x = { placeholder = "0" },
					   y = { placeholder = "0" }, 
					   block = { placeholder = "0" }, 
					   rot = { placeholder = "0" }, 
					   cfg = { placeholder = "0" } } },
		{ name = "UnitGetblock",
		  template = tr("Unit CtrlGetBlock x %in.x y %in.y\ntype %in.type building %in.bld floor %in.flr"),
		  options  = { x = { placeholder = "0" },
					   y = { placeholder = "0" }, 
					   type = { placeholder = "0" }, 
					   bld = { placeholder = "0" }, 
					   flr = { placeholder = "0" } } },
		{ name = "UnitWithin",
		  template = tr("Unit CtrlWithin %in.x %in.y radius %in.radius result %in.result"),
		  options  = { x = { placeholder = "0" },
					   y = { placeholder = "0" }, 
					   radius = { placeholder = "0" }, 
					   result = { placeholder = "0" } } },
		{ name = "UnitUnbind",
		  template = tr("Unit unbind"),
		  options  = {} },
		{ name = "UnitRadar",
		  template = tr("Unit Radar target %op.s1 %op.s2 %op.s3\norder %in.num sort %op.radar %in.result"),
		  options  = { s1 = { items = SORTS, changed = _stub }, 
					   s2 = { items = SORTS, changed = _stub }, 
					   s3 = { items = SORTS, changed = _stub }, 
					   num = { placeholder = "1" },
					   radar = { items = RADAR_KEYS, changed = _stub }, 
					   result = { placeholder = "result" } } },
		{ name = "UnitLocate",
		  template = tr("Unit Locate %op.find group %op.group enemy %in.enemy %in.res\n" +
						"outX %in.outX outY %in.outY found %in.found building %in.building"),
		  options  = { find = { items = ["ore","building","spawn","damaged"], changed = _stub },
					   group = { items = ["core","storage","generator","turret","factory",
										  "repair","battery","reactor","drill","shield"], changed = _stub },
					   enemy = { placeholder = "true" }, 
					   outX = { placeholder = "outx" },
					   outY = { placeholder = "outy" }, 
					   found = { placeholder = "found" }, 
					   building = { placeholder = "building" } } },
	],
}
